### ISSUE TITLE
Repackage Kaltura Player SDK as source distribution

### ISSUE THREAD

**Issue by andrewjl-mux** [muxinc/mux-stats-sdk-kaltura-ios#65]
```[tasklist]
### Tasks
- [x] Validate Xcode 15 support
- [x] Release repackaged SDK - v3.0.0
- [x] Deploy to Cocoapods Trunk
```

**Comment by andrewjl-mux** [comment]
#63
